[package]
name = "atelier-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
atelier-core = { path = "../core" }
capnp = "0.12"
capnp-rpc = "0.12"
tokio = { version = "0.2", features = ["io-std", "rt-util", "tcp", "io-util"] }
tokio-util = { version = "0.2", features = ["codec"] }
futures = "0.3"
atelier-schema = { path = "../schema" }
uuid = "0.8"
async-trait = "0.1.22"
crossterm = { version = "0.14.2", features = ["event-stream"] }
defer = "0.1.0"
