[package]
name = "atelier-core"
version = "0.1.0"
edition = "2018"

[features]
serde-1 = ["serde"]
importer_context = ["inventory"]
futures-tokio-compat-1 = ["futures-tokio-compat"]

[dependencies]
uuid = { version = "0.8", features = [ "v4" ] }
proc-macro-hack = "0.5"
asset-uuid = { path = "./asset-uuid" }
serde = { version = "1.0", optional = true, features = ["derive"] }
inventory = { version = "0.1", optional = true }
futures = "0.3"
futures-tokio-compat = { git = "https://github.com/dwrensha/futures-tokio-compat", branch = "tokio-0.2", optional = true }

[dev-dependencies]
serde_json = "1.0"
bincode = "1.2"
